spring:
  profiles:
    active: pro

---
# environment development
spring:
  config:
    activate:
      on-profile: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
<<<<<<< HEAD
    password: 123456
=======
    password: 123123
>>>>>>> main
    url: jdbc:mysql://localhost:3306/db_computer_communication

server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
<<<<<<< HEAD
=======

---
# environment production
spring:
  config:
    activate:
      on-profile: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.113.218.167:3306/db_geek_home


server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
   map-underscore-to-camel-case: true

>>>>>>> main
