spring:
  profiles:
    active: prod

server:
  servlet:
    context-path: /api

---
# dev env
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/db_computer_communication

server:
  port: 81

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
# prod env
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.113.218.167:3306/db_geek_home

server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl